# Generated by Django 5.1.1 on 2024-09-26 13:50

import django_resized.forms
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_name", models.CharField(max_length=80)),
                ("body", models.TextField()),
                (
                    "image",
                    django_resized.forms.ResizedImageField(
                        crop=None,
                        default="",
                        force_format="WEBP",
                        keep_meta=True,
                        quality=75,
                        scale=None,
                        size=[400, None],
                        upload_to="laura_board_posts/",
                    ),
                ),
                ("posted_date", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-posted_date"],
            },
        ),
    ]
